# -*- coding: utf-8 -*-
"""TennisPredictions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIOPQxWkJU-WR7Rbz_kQjPJizfHcqSF2
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, log_loss, roc_auc_score

np.random.seed(42)
pd.set_option('display.max_columns', None)

#full github of data
#https://github.com/Aneeshers/tennis-sackmann-archive

years = range(2000,2024)
dfs = []

for year in years:
  url = f"https://raw.githubusercontent.com/Aneeshers/tennis-sackmann-archive/refs/heads/main/atp/atp_matches_{year}.csv"

  dfs.append(pd.read_csv(url))

df = pd.concat(dfs, ignore_index=True)

df.head()

filtered_df = df.drop(columns=["score", "minutes", "w_ace", "w_df", "w_svpt", "w_1stIn", "w_1stWon", "w_2ndWon", "w_SvGms", "w_bpSaved", "w_bpFaced", "l_ace", "l_df", "l_svpt", "l_1stIn", "l_1stWon", "l_2ndWon", "l_SvGms", "l_bpSaved", "l_bpFaced"])
filtered_df["tourney_date"] = pd.to_datetime(filtered_df["tourney_date"], format="%Y%m%d")
filtered_df.sort_values("tourney_date").reset_index(drop=True)

filtered_df.head()

# Original matches: winner is Player 1
df1 = filtered_df.copy()

df1["rank_diff"] = df1["winner_rank"] - df1["loser_rank"]
df1["rank_points_diff"] = df1["winner_rank_points"] - df1["loser_rank_points"]
df1["age_diff"] = df1["winner_age"] - df1["loser_age"]
df1["height_diff"] = df1["winner_ht"] - df1["loser_ht"]

df1["target"] = 1


# Reversed matches: loser is Player 1
df2 = filtered_df.copy()

df2["rank_diff"] = df2["loser_rank"] - df2["winner_rank"]
df2["rank_points_diff"] = df2["loser_rank_points"] - df2["winner_rank_points"]
df2["age_diff"] = df2["loser_age"] - df2["winner_age"]
df2["height_diff"] = df2["loser_ht"] - df2["winner_ht"]

df2["target"] = 0

model_df = pd.concat([df1, df2], ignore_index=True)

filtered_df.head(10)

features = [
    "rank_diff",
    "rank_points_diff",
    "age_diff",
    "height_diff"
]

model_df = model_df.dropna(subset=features).copy()

#training dataframe -> 2000-2018
training_df = model_df[model_df["tourney_date"].dt.year <= 2018]

#validation dataframe -> 2019-2021
validation_df = model_df[(model_df["tourney_date"].dt.year >= 2019) & (model_df["tourney_date"].dt.year <= 2021)]

#test dataframe -> 2022+
test_df = model_df[model_df["tourney_date"].dt.year >= 2022]

X_train = training_df[features]
y_train = training_df["target"]

X_val = validation_df[features]
y_val = validation_df["target"]

X_test = test_df[features]
y_test = test_df["target"]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

y_val_pred = model.predict(X_val_scaled)
y_val_prob = model.predict_proba(X_val_scaled)[:,1]

print(y_val_pred)
print(y_val_prob)

rank_baseline_pred = (X_val["rank_diff"] < 0).astype(int)
rank_accuracy = accuracy_score(y_val, rank_baseline_pred)

accuracy = accuracy_score(y_val, y_val_pred)
loss = log_loss(y_val, y_val_prob)
auc = roc_auc_score(y_val, y_val_prob)

print(f'Baseline Accuracy: {rank_accuracy:.8f}')
print(f'Accuracy: {accuracy:.8f}')
print(f'Loss: {loss:.8f}')
print(f'AUC: {auc:.8f}')

from sklearn.ensemble import RandomForestClassifier

rfc_model = RandomForestClassifier(n_estimators = 100, max_depth = 8, n_jobs=-1, random_state=42)

rfc_model.fit(X_train, y_train)

rfc_pred = rfc_model.predict(X_val)
rfc_prob = rfc_model.predict_proba(X_val)[:,-1]

rfc_accuracy = accuracy_score(y_val, rfc_pred)
rfc_loss = log_loss(y_val, rfc_prob)
rfc_auc = roc_auc_score(y_val, rfc_prob)

print(f"Random Forest Accuracy: {rfc_accuracy:.8f}")
print(f"Random Forest Log Loss: {rfc_loss:.8f}")
print(f"Random Forest AUC: {rfc_auc:.8f}")

from xgboost import XGBClassifier

xgb_model = XGBClassifier(n_estimators=300, max_depth = 4, learning_rate=0.05, subsample=0.8,colsample_bytree=0.8, n_jobs = -1, random_state=42)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_val)
xgb_prob = xgb_model.predict_proba(X_val)[:, 1]

xgb_accuracy = accuracy_score(y_val, xgb_pred)

xgb_loss = log_loss(y_val, xgb_prob)

xgb_auc = roc_auc_score(y_val, xgb_prob)

print(f"XGBoost Accuracy: {xgb_accuracy:.8f}")
print(f"XGBoost Log Loss: {xgb_loss:.8f}")
print(f"XGBoost AUC: {xgb_auc:.8f}")